version: '3.2'
services:
  db_mysql:
    container_name: db_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: cafe
    ports:
      - 3306:3306
    volumes:
      - ./db/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - my-network
  cafe_manager:
    container_name: cafe_manager
    image: cafe_manager:0.0.0
    build: 
      context: .
      dockerfile: Dockerfile
    privileged: true
    command: cafe_manager
      - --dbaddr=db_mysql
      - --dbport=3306
      - --dbuser=user
      - --dbpass=1234
      - --dbname=cafe
      - --port=3000
    ports:
      - 3000:3000
    depends_on:
      - db_mysql
    networks:
      - my-network
networks:
  my-network: